"""empty message

Revision ID: 3841053ead6c
Revises: 8f813fae626d
Create Date: 2020-07-02 02:17:25.491769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3841053ead6c'
down_revision = '8f813fae626d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(length=5000), nullable=True))
    op.drop_column('product', 'Description')
    op.alter_column('sub_inventory', 'delivery',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('sub_inventory', 'paid')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('sub_inventory', sa.Column('paid', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
    op.alter_column('sub_inventory', 'delivery',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('product', sa.Column('Description', sa.VARCHAR(length=5000), nullable=True))
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
